### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by falsovsky** [talvasconcelos/cv#1]
https://github.com/talvasconcelos/cv/blob/master/index.html#L52 - Sarting

https://github.com/talvasconcelos/cv/blob/master/index.html#L62 - Olds ou Asks?

Vi o teu sayte mencionado no reddit, espero que nao fiques chateado :-P

**Comment by talvasconcelos** [comment]
Porque havia de ficar chateado?! Obrigado pela chamada de atenção, vou corrigir!!
